### ISSUE TITLE
SEO Upgrades

### ISSUE THREAD

**Issue by trezy** [RollForGuild/rollforguild.com#53]
Some updates are necessary for better SEO performance.

## Acceptance Criteria
- [ ] [#50] All public pages have titles and descriptions (cc @JoshWhelan)
- [ ] [#50] All public pages have descriptions (cc @JoshWhelan)
- [ ] [#49] All images are optimized
- [x] [#47] The website serves up `/robots.txt`
- [x] [#48] The website serves up `/sitemap.xml`
